presets:
  Music:
    preset:
      - "YouTube Releases"
      - "Max MP3 Quality"
    embed_thumbnail: True
    square_thumbnail: True
    ytdl_options:
      extractor_args:
        youtube:
          lang:
            - "ja"
      cookiefile: "/cookies.txt"

    overrides:
      # プレイリストタイトルのうちアルバム名を抽出する
      track_album: >-
        { %regex_sub("^(Album - |アルバム - )", "", playlist_title) }

      album_dir: "{track_album_sanitized}"
